package com.ftn.sbnz.model.models.enums;

public enum SkinBenefit {
    ANTI_AGE,
    HYDRATION,
    DARK_SPOT_REMOVAL,
    HYPERPIGMENTATION_REDUCTION,
    SUN_PROTECTION,
    ACNE_REDUCING,
    SKIN_TEXTURE_IMPROVEMENT,
    IRRITATION_CALMING,
    DETOXIFICATION,
    CLEANSING,
    SKIN_TONE_EVENING,
    MOISTURIZING
}

